// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Viberz.Infrastructure.Data;

#nullable disable

namespace Viberz.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260106135935_Migration-20260106-Add-Guest-Playlists")]
    partial class Migration20260106AddGuestPlaylists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Viberz.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsGuestGenre")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsGuestGenre = false,
                            Name = "Bass House",
                            SpotifyId = "0Y2Dt0Vfg3VSYBKd2BRGyx"
                        },
                        new
                        {
                            Id = 2,
                            IsGuestGenre = false,
                            Name = "EDM Trap",
                            SpotifyId = "4QXVqNH5XVCDAlAS1HocVW"
                        },
                        new
                        {
                            Id = 3,
                            IsGuestGenre = false,
                            Name = "Dubstep",
                            SpotifyId = "6qxaYSiO7LVEJE6dsjC9QU"
                        },
                        new
                        {
                            Id = 4,
                            IsGuestGenre = false,
                            Name = "Drum & Bass",
                            SpotifyId = "0UkGPS5GMhO0QmJx9MvbJm"
                        },
                        new
                        {
                            Id = 5,
                            IsGuestGenre = false,
                            Name = "Tech House",
                            SpotifyId = "2hDT4wx3d3hFNwKMgIKNiB"
                        },
                        new
                        {
                            Id = 6,
                            IsGuestGenre = false,
                            Name = "Hard Techno",
                            SpotifyId = "6LsBdAO09tOMgkt8RJ5ktv"
                        },
                        new
                        {
                            Id = 7,
                            IsGuestGenre = false,
                            Name = "Garage UK",
                            SpotifyId = "1HzqMHV1TMMZjD0POdlww0"
                        },
                        new
                        {
                            Id = 8,
                            IsGuestGenre = false,
                            Name = "Hyper Techno",
                            SpotifyId = "5WhatiRekXXBNRXeO6jXmV"
                        },
                        new
                        {
                            Id = 9,
                            IsGuestGenre = false,
                            Name = "Stutter House",
                            SpotifyId = "08oVyHSMPq79FNRvdxnnPK"
                        },
                        new
                        {
                            Id = 10,
                            IsGuestGenre = false,
                            Name = "Progressive House",
                            SpotifyId = "3qSskUmTASIyuIKWTfZT2J"
                        },
                        new
                        {
                            Id = 11,
                            IsGuestGenre = false,
                            Name = "Mid Tempo",
                            SpotifyId = "3hUcNAkx9fQ20kREAR22A7"
                        },
                        new
                        {
                            Id = 12,
                            IsGuestGenre = false,
                            Name = "Future House",
                            SpotifyId = "6irfmXy7b12btvyYPrpEA4"
                        },
                        new
                        {
                            Id = 13,
                            IsGuestGenre = false,
                            Name = "Hardstyle",
                            SpotifyId = "2exynTofOAgLHuonZaImx2"
                        },
                        new
                        {
                            Id = 14,
                            IsGuestGenre = false,
                            Name = "Big Room",
                            SpotifyId = "4bApSsicsTPhjR3zt2UPmg"
                        },
                        new
                        {
                            Id = 101,
                            IsGuestGenre = true,
                            Name = "Bass House",
                            SpotifyId = "0toSf2qoXdSYTsICqzGUbr"
                        },
                        new
                        {
                            Id = 102,
                            IsGuestGenre = true,
                            Name = "EDM Trap",
                            SpotifyId = "6RZZqNGqXjAIs9KiOTmOEH"
                        },
                        new
                        {
                            Id = 103,
                            IsGuestGenre = true,
                            Name = "Dubstep",
                            SpotifyId = "3M3vT1UGM1PjPAbwqIJpxB"
                        },
                        new
                        {
                            Id = 104,
                            IsGuestGenre = true,
                            Name = "Drum & Bass",
                            SpotifyId = "5GbXD4WM4m85yfn89MhGlV"
                        },
                        new
                        {
                            Id = 105,
                            IsGuestGenre = true,
                            Name = "Future House",
                            SpotifyId = "1HVD4YYRmfUL6JEyEXmedp"
                        });
                });

            modelBuilder.Entity("Viberz.Domain.Entities.LikedPlaylists", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LikedPlaylists");
                });

            modelBuilder.Entity("Viberz.Domain.Entities.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("GenreList")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpotifyPlaylistId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Viberz.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("FavoriteArtists")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("FavoriteGenres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Viberz.Domain.Entities.Whitelist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Whitelist");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "thomas.bfrd@gmail.com"
                        });
                });

            modelBuilder.Entity("Viberz.Domain.Entities.XpGrades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MinXp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("XpGrades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GradeName = "Newbie",
                            Level = 1,
                            MinXp = 0
                        },
                        new
                        {
                            Id = 2,
                            GradeName = "Beat Beginner",
                            Level = 2,
                            MinXp = 50
                        },
                        new
                        {
                            Id = 3,
                            GradeName = "Bass Novice",
                            Level = 3,
                            MinXp = 120
                        },
                        new
                        {
                            Id = 4,
                            GradeName = "Stage Starter",
                            Level = 4,
                            MinXp = 250
                        },
                        new
                        {
                            Id = 5,
                            GradeName = "Drop Apprentice",
                            Level = 5,
                            MinXp = 450
                        },
                        new
                        {
                            Id = 6,
                            GradeName = "Groove Tinkerer",
                            Level = 6,
                            MinXp = 800
                        },
                        new
                        {
                            Id = 7,
                            GradeName = "Crowd Controller",
                            Level = 7,
                            MinXp = 1300
                        },
                        new
                        {
                            Id = 8,
                            GradeName = "Drop Disciple",
                            Level = 8,
                            MinXp = 2100
                        },
                        new
                        {
                            Id = 9,
                            GradeName = "Festival Vanguard",
                            Level = 9,
                            MinXp = 3200
                        },
                        new
                        {
                            Id = 10,
                            GradeName = "Bass Boss",
                            Level = 10,
                            MinXp = 4700
                        },
                        new
                        {
                            Id = 11,
                            GradeName = "Sound Sorcerer",
                            Level = 11,
                            MinXp = 6700
                        },
                        new
                        {
                            Id = 12,
                            GradeName = "Legendary Master",
                            Level = 12,
                            MinXp = 9500
                        });
                });

            modelBuilder.Entity("Viberz.Domain.Entities.XpHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EarnedXp")
                        .HasColumnType("integer");

                    b.Property<int?>("Genre")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("XpHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
