// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viberz;

#nullable disable

namespace Viberz.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250829154231_Fix-Columns-User-DataBase")]
    partial class FixColumnsUserDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Viberz.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bass House"
                        },
                        new
                        {
                            Id = 2,
                            Name = "EDM Trap"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dubstep"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drum & Bass"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tech House"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hard Techno"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Garage UK"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hyper Techno"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Stutter House"
                        });
                });

            modelBuilder.Entity("Viberz.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FavoriteArtists")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "favoriteArtists");

                    b.Property<string>("FavoriteGenres")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "favoriteGenres");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "image");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "userName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
